on: [ pull_request ]

# Auto-merge pull requests opened by ipldbot, if all tests pass.
# This reduces the friction associated with updating with our workflows.
jobs:
  automerge:
    if: github.event.pull_request.user.login == 'ipldbot'
    runs-on: ubuntu-latest
    steps:
    - name: Wait on tests
      uses: lewagon/wait-on-check-action@v0.2
      with:
        ref: ${{ github.event.pull_request.head.sha }}
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        wait-interval: 10
        running-workflow-name: 'automerge' # the name of this job
    - name: Merge PR
      uses: pascalgn/automerge-action@v0.13.1
      env:
        GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
        MERGE_LABELS: ""
        MERGE_DELETE_BRANCH: true
