on: push

jobs:
  copy:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        num: [ 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50 ]
    env:
      GITHUB_USER: "ipldbot"
      GITHUB_EMAIL: "ipldbot@users.noreply.github.com"
      TARGET_REPO: "marten-seemann-test/target"
      TARGET_REPO_DIR: "tempate-repo"
    name: "copy ${{ matrix.num }}"
    steps:
    - run: cat "$GITHUB_EVENT_PATH" | jq -M .
    - name: Checkout ${{ matrix.cfg.target }}
      uses: actions/checkout@v2
      with:
        path: ${{ env.TARGET_REPO_DIR }}
        repository: ${{ env.TARGET_REPO }}
        token: ${{ secrets.IPLDBOT_GITHUB_TOKEN }}
        persist-credentials: true
    - name: Create a file
      run: echo "file ${{ matrix.num }}" > ${{ env.TARGET_REPO_DIR }}/file_${{ matrix.num }}.txt
    - name: Create Pull Request
      uses: peter-evans/create-pull-request@052fc72b4198ba9fbc81b818c6e1859f747d49a8 #v3.8.2
      with:
        path: ${{ env.TARGET_REPO_DIR }}
        title: "copy ${{ matrix.num}} (${{ github.event.after }})"
        token: ${{ secrets.IPLDBOT_GITHUB_TOKEN }}
        committer: ${{ env.GITHUB_USER }} <${{ env.GITHUB_EMAIL }}>
        author: ${{ env.GITHUB_USER }} <${{ env.GITHUB_EMAIL }}>
        branch: sync_${{ github.event.after }}_${{ matrix.num }}
        delete-branch: true
